### ISSUE TITLE
Container keeps running as unhealthy, how to fix it?

### ISSUE THREAD

**Issue by BobWs** [crashvb/getmail-docker#2]
Hi,

I have manage to setup your getmail container and it is working for me to fetch my mail from Gmail,
But the healthcheck keeps hanging on unhealthy, is there a easy way to fix this?

TIA

**Comment by crashvb** [comment]
Ah, I see the problem ... I'll refactor the script(s) to correct the issue; thank you for reporting :)

**Comment by crashvb** [comment]
Should be fixed in:
* crashvb/getmail:202112131138 
* crashvb/getmail:33847fbadc1c
* crashvb/getmail:latest

```bash
f2bbc4141466   crashvb/getmail:202112131138      "/sbin/entrypoint /u…"   About a minute ago   Up About a minute (healthy)
```
